version: '3'

services:
  redis:
    hostname: redis
    container_name: redis_db
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    expose:
      - "6379"
    networks:
      - offertiamo_development

  web:
    container_name: webserver_flask
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      REDIS_DATABASE_HOST: "redis"
    command: [ 'python3', './main.py' ]
    depends_on:
      - redis
      - worker
    networks:
      - offertiamo_development
  
  worker:
    container_name: worker_celery
    build: .
    volumes:
      - .:/code
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/1"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      BROKER_URL: "redis://redis:6379/1"
      RESULT_BACKEND: "redis://redis:6379/1"
      REDIS_DATABASE_HOST: redis
    command: [ "celery", "-A", "services.celery_services.celery_app", "worker" ]
    depends_on:
      - redis
    networks:
      - offertiamo_development

networks:
  offertiamo_development:
