version: '3'

services:
  redis:
    container_name: redis_db
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
  web:
    container_name: webserver_flask
    build: .
    volumes:
      - .:/code
    ports:
      - 5000:5000
    command: python main.py