version: '3'

services:
  redis:
    container_name: redis_db
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    expose: 
      - "6379"
    networks:
      - project_networks

  web:
    container_name: webserver_flask
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    expose:
      - "5000"
    environment:
            - FLASK_APP=main.py
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - redis
    networks:
      - project_networks
    

networks:
    project_networks:
